variables:
  TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
  - test
  - release
  - deploy

include:
  project: educs/gitlab-ci-templates
  file: .npm-template.yml
  ref: HEAD

#in general login

test:
  stage: test
  image: node:17-alpine
  tags:
    - docker
  script:
    - npm ci --cache .npm --prefer-offline
    - npm test

release-image:
  stage: release
  tags:
    - docker builder
  before_script:
  script:
    - false && docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $RELEASE_IMAGE .
    - docker push $RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  image: curlimages/curl
  script:
    - "curl -X POST -F token=$TRIGGER_TOKEN -F ref=$CI_COMMIT_BRANCH https://gitlab.tba-hosting.de/api/v4/projects/317/trigger/pipeline"
  only:
    - master