stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker builder
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  image: curlimages/curl
  script:
    - "curl -X POST -F token=$TRIGGER_TOKEN -F ref=$CI_COMMIT_BRANCH https://gitlab.tba-hosting.de/api/v4/projects/317/trigger/pipeline"
